package com.github.codehive.model.enums;

public enum AdminAuditAction {
    USER_CREATED,
    USER_PROFILE_UPDATED,
    USER_ROLE_CHANGED,
    USER_BLOCKED,
    USER_UNBLOCKED,
    USER_DELETED,
    USER_SCOPES_CHANGED,
    CSV_REGISTRATION_SUBMITTED,
    CSV_REGISTRATION_COMPLETED
}
