spring.config.import=optional:file:.env[.properties]
spring.application.name=worker
# Minio Configuration
minio.url=${MINIO_URL:defaultMinioUrl}
minio.accessKey=${MINIO_ACCESS_KEY:defaultAccessKey}
minio.secretKey=${MINIO_SECRET_KEY:defaultSecretKey}
minio.bucketName=${MINIO_BUCKET_NAME:defaultBucketName}

# RabbitMQ Configuration
spring.rabbitmq.host=${RABBITMQ_HOST:defaultRabbitHost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:defaultRabbitUser}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:defaultRabbitPassword}
spring.rabbitmq.queue=${RABBITMQ_QUEUE:defaultQueue}
spring.rabbitmq.result.queue=${RABBITMQ_RESULT_QUEUE:defaultResultQueue}