spring.config.import=optional:file:.env[.properties]
spring.application.name=worker
# Minio Configuration
minio.url=${MINIO_URL:defaultMinioUrl}
minio.accessKey=${MINIO_ACCESS_KEY:defaultAccessKey}
minio.secretKey=${MINIO_SECRET_KEY:defaultSecretKey}
minio.bucketName=${MINIO_BUCKET_NAME:defaultBucketName}

# RabbitMQ Configuration
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
rabbitmq.queue=${RABBITMQ_QUEUE:codehive_queue}
rabbitmq.result.queue=${RABBITMQ_RESULT_QUEUE:codehive_result_queue}
rabbitmq.test-generation.queue=${RABBITMQ_TEST_GENERATION_QUEUE:codehive_test_generation_queue}
rabbitmq.test-generation.result.queue=${RABBITMQ_TEST_GENERATION_RESULT_QUEUE:codehive_test_generation_result_queue}
