import { LineChart, Line, XAxis, YAxis, Tooltip, Legend, ResponsiveContainer } from "recharts";
import type { Summary, Technical } from "./types";
export const usagePanel = "rounded-2xl border border-gray-200 dark:border-gray-800 bg-white dark:bg-dark-surface p-5";
export const usageInput = "rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-dark-card px-3 py-2 text-sm";
export function measured(value: number | null | undefined) { return value == null ? "Not measured" : value.toLocaleString(); }
export function TechnicalUsage({ value, startedAt }: { value: Technical; startedAt: string | null }) {
  return <div className="space-y-2 text-sm">
    <p>Provider calls: {value.calls.toLocaleString()} · Uncertain results: {value.uncertain} · Caller timeouts: {value.callerTimeouts}</p>
    <p>Known input tokens: {measured(value.knownInputTokens)} · Known output tokens: {measured(value.knownOutputTokens)} · Known total tokens: {measured(value.knownTotalTokens)}</p>
    <p>Measurement coverage: {value.coveragePercent == null ? "Not measured" : `${value.coveragePercent}%`} ({value.measuredCalls}/{value.calls} calls). {value.unknownCalls > 0 && "Tokens measured partially; actual consumption may be higher."}</p>
    <p>First recorded call: {startedAt ? new Date(startedAt).toLocaleString() : "No recorded calls yet"}.</p>
    <p>Provider latency: {value.averageLatencyMs == null ? "Not measured" : `${value.averageLatencyMs} ms`} ({value.latencySamples} samples).</p>
    <p className="text-gray-500 dark:text-gray-400">Tokens describe technical work, including reviews and failed questions. They are not money or answer quota. Provider totals may differ from input plus output.</p>
  </div>;
}
export function UsageSummary({ value, personal = false }: { value: Summary; personal?: boolean }) {
  const e = value.educational;
  const cards = [["Answers used", e.responses], ["Questions registered", e.requests], ["Questions without answer", e.blocked + e.failed + e.cancelled], ["In progress", e.pending], ["Students with activity", e.activeUsers]] as const;
  return <div className="space-y-4">
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{cards.filter(([label]) => !personal || label !== "Students with activity").map(([label, count]) => <div className={usagePanel} key={label}><p className="text-xs text-gray-500 dark:text-gray-400">{label}</p><p className="mt-2 text-3xl font-semibold">{count.toLocaleString()}</p></div>)}</div>
    <div className={`${usagePanel} space-y-2 text-sm`}><h2 className="font-semibold">{value.label}</h2><p>{value.filters.from ? `${new Date(value.filters.from).toISOString()} ≤ start < ${new Date(value.filters.to!).toISOString()}` : "All recorded history"}</p><p>Educational redirections use one answer. Questions without a delivered answer do not use answer quota, even when technical work occurred.</p><p>Answers delivered: {e.completed} educational · {e.redirected} redirections. Regenerations: {e.regenerations}.</p>{e.historicalUninstrumented > 0 && <p role="status" className="text-amber-700 dark:text-amber-400">{e.historicalUninstrumented} historical questions have no call instrumentation. Historical tokens and calls cannot be reconstructed.</p>}{value.currentPolicy && <p>Current policy: {value.currentPolicy.enabled ? `${value.currentPolicy.maximumCurrent} lifetime answers per student · ${value.currentPolicy.level?.replaceAll("_", " ")}` : "Disabled · current limit 0"}. Current policy does not describe historical permissions.</p>}<p className="text-xs text-gray-500">Generated {new Date(value.generatedAt).toLocaleString()}. Each response has its own timestamp.</p></div>
    {value.trend.some(day => day.requests > 0 || day.calls > 0) ? <section className={usagePanel} aria-label="Daily AI usage trend"><h2 className="font-semibold">Daily trend (UTC)</h2><p className="text-xs text-gray-500 mb-4">Questions by question start; provider calls by call start. Units: counts per day.</p><div className="h-64" aria-hidden="true"><ResponsiveContainer width="100%" height="100%"><LineChart data={value.trend}><XAxis dataKey="day" tick={{ fontSize: 10 }} /><YAxis allowDecimals={false} /><Tooltip /><Legend /><Line dataKey="requests" name="Questions" stroke="#2563eb" strokeDasharray="4 2" /><Line dataKey="responses" name="Answers used" stroke="#16a34a" /><Line dataKey="calls" name="Provider calls" stroke="#9333ea" strokeDasharray="2 2" /></LineChart></ResponsiveContainer></div><details><summary className="cursor-pointer text-sm">Daily data table</summary><div className="overflow-x-auto"><table className="w-full text-sm"><caption className="sr-only">Daily usage counts and known tokens, UTC</caption><thead><tr>{["Date", "Questions", "Answers used", "Calls", "Known tokens"].map(h => <th className="p-2 text-left" key={h}>{h}</th>)}</tr></thead><tbody>{value.trend.map(d => <tr key={d.day}><th scope="row" className="p-2 text-left">{d.day}</th><td>{d.requests}</td><td>{d.responses}</td><td>{d.calls}</td><td>{measured(d.knownTotalTokens)}</td></tr>)}</tbody></table></div></details></section> : <p className={usagePanel}>{value.filters.from ? "No activity in this date range." : "Choose a date range to display daily trends."}</p>}
    <details className={usagePanel}><summary className="cursor-pointer font-semibold">Educational breakdown</summary><div className="mt-4 space-y-2 text-sm"><p>Questions blocked: {e.blocked} · Failed: {e.failed} · Cancelled: {e.cancelled}.</p><p>Students with a delivered answer: {e.respondingUsers}. Educational response latency: {e.averageLatencyMs == null ? "Not measured" : `${e.averageLatencyMs} ms`} ({e.latencySamples} samples).</p><p>Editor context opt-ins: {e.editorOptIns} · Execution context opt-ins: {e.executionOptIns}. These count consent choices, not context actually sent.</p><p>Requested assistance levels: {Object.entries(e.requestedLevels).map(([level, count]) => `${level.replaceAll("_", " ")}: ${count}`).join(" · ") || "Not measured"}.</p><p>Delivered assistance levels: {Object.entries(e.deliveredLevels).map(([level, count]) => `${level.replaceAll("_", " ")}: ${count}`).join(" · ") || "No delivered level recorded"}.</p><p className="text-gray-500">States reflect current outcomes of questions started in the range. Usage frequency does not measure learning, dependence or cheating.</p></div></details>
    <details className={usagePanel}><summary className="cursor-pointer font-semibold">Technical usage and measurement coverage</summary><div className="mt-4"><TechnicalUsage value={value.technical} startedAt={value.instrumentationStartedAt} /></div></details>
  </div>;
}
